# Generated by Django 3.2.5 on 2021-07-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_department_date_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
